name: todo-list-pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Build e Testes com Maven
        run: 'mvn clean verify'
        working-directory: tasks

      - name: Docker Build (se os testes passarem)
        run: docker build -t tasks-app .
        working-directory: tasks
